# Generated by Django 5.2.7 on 2025-10-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('image', 'Сүрөт'), ('video', 'Видео')], default='image', max_length=10)),
                ('title', models.CharField(max_length=100, verbose_name='Аталышы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Сүрөт (эгер сүрөт болсо)')),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery_videos/', verbose_name='Видео (эгер видео болсо)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
