# Generated by Django 5.2.7 on 2025-10-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Айлык акы'), ('rent', 'Ижара акысы'), ('marketing', 'Маркетинг'), ('raw_materials', 'Чийки заттар'), ('utilities', 'Коммуналдык кызматтар'), ('other', 'Башка')], max_length=50, verbose_name='Категориясы')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Суммасы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сүрөттөмөсү')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Датасы')),
            ],
            options={
                'verbose_name': 'Чыгаша',
                'verbose_name_plural': 'Чыгашалар',
                'ordering': ['-date'],
            },
        ),
    ]
