# Generated by Django 5.2.7 on 2025-10-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты')),
                ('text', models.TextField(verbose_name='Пикири')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Датасы')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Көрүнсүнбү')),
            ],
            options={
                'verbose_name': 'Сын-пикир',
                'verbose_name_plural': 'Сын-пикирлер',
                'ordering': ['-created_at'],
            },
        ),
    ]
