"""
Django settings for food_order_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fk=5ch888gdfn!9w2(hmqn^1()%p%w1u*p(h8%a2b#d(9y%4o@'


DEBUG = True

ALLOWED_HOSTS = []



INSTALLED_APPS = [
    'jazzmin',
    'expenses',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',   
    'products',         
    'orders',          
    'accounts',         
    'corsheaders', 
    'rest_framework.authtoken',
    'feedback',
    'gallery',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'food_order_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'food_order_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", 
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [

        'rest_framework.permissions.IsAuthenticated',
    ]
}


JAZZMIN_SETTINGS = {

    "site_title": "Даяр Дасторкон Admin",

    
    "site_header": "Даяр Дасторкон",


    "welcome_sign": "Даяр Дасторкон Башкаруу Панелине кош келиңиз",


    "copyright": "Даяр Дасторкон Ltd.",


    "order_with_respect_to": [
        "products", "products.Product", "products.Category",
        "orders", "orders.Order", "orders.Expense",
        "gallery", "feedback", "accounts", "auth",
    ],


    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts": "fas fa-user-circle",
        "products.Product": "fas fa-hamburger",
        "products.Category": "fas fa-tags",
        "orders.Order": "fas fa-shopping-cart",

        "orders.Expense": "fas fa-money-bill-wave",
        "gallery.GalleryItem": "fas fa-images",
        "feedback.Feedback": "fas fa-comments",
    },
    

    "show_ui_builder": True,
}

JAZZMIN_SETTINGS = {

    "site_title": "Даяр Дасторкон Admin",

    "site_header": "Даяр Дасторкон",


    "welcome_sign": "Даяр Дасторкон Башкаруу Панелине кош келиңиз",

    "copyright": "Даяр Дасторкон Ltd.",


    "order_with_respect_to": [
        "products", "products.Product", "products.Category",
        "orders", "orders.Order", 
        "expenses",
        "gallery", "feedback", "accounts", "auth",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts": "fas fa-user-circle",
        "products.Product": "fas fa-hamburger",
        "products.Category": "fas fa-tags",
        "orders.Order": "fas fa-shopping-cart",
        "expenses.Expense": "fas fa-money-bill-wave",
        "gallery.GalleryItem": "fas fa-images",
        "feedback.Feedback": "fas fa-comments",
    },
    

    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False, 
    "accent": "accent-primary",
    
-
    "navbar": "navbar-white navbar-light",  
    "no_navbar_border": False,
    "sidebar": "sidebar-light-primary",   
    "theme": "default",                  
    "dark_mode_theme": None,             


    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "button_classes": {
        "primary": "btn-outline-primary", 
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


STATIC_ROOT = BASE_DIR / 'staticfiles'
