# Generated by Django 5.2.7 on 2025-10-12 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Айлык акы'), ('rent', 'Ижара акысы'), ('marketing', 'Маркетинг'), ('raw_materials', 'Чийки заттар'), ('utilities', 'Коммуналдык кызматтар'), ('other', 'Башка')], max_length=50, verbose_name='Категориясы')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Суммасы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сүрөттөмөсү')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Датасы')),
            ],
            options={
                'verbose_name': 'Чыгаша',
                'verbose_name_plural': 'Чыгашалар',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Заказ берилген күнү')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Жеткирүү дареги')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Жалпы суммасы')),
                ('status', models.CharField(choices=[('pending', 'Күтүүдө'), ('processing', 'Аткарылууда'), ('delivered', 'Жеткирилди'), ('cancelled', 'Баш тартылды'), ('expired', 'Мөөнөтү өттү')], default='pending', max_length=20, verbose_name='Статусу')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Жеткирилген күнү')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Баш тартылган күнү')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Төлөм ыкмасы')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Төлөндүбү')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Колдонуучу')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказдар',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Саны')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бирдигинин баасы')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказдын элементи',
                'verbose_name_plural': 'Заказдын элементтери',
            },
        ),
    ]
