# Generated by Django 5.2.7 on 2025-10-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Күтүүдө'), ('processing', 'Аткарылууда'), ('delivered', 'Жеткирилди'), ('cancelled', 'Баш тартылды'), ('expired', 'Мөөнөтү өткөн')], default='pending', max_length=20, verbose_name='Статусу'),
        ),
    ]
