# Generated by Django 5.2.7 on 2025-10-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн (Касса)')], default='online', max_length=10, verbose_name='Заказдын түрү'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Күтүүдө'), ('processing', 'Аткарылууда'), ('delivered', 'Жеткирилди'), ('cancelled', 'Баш тартылды'), ('expired', 'Мөөнөтү өттү')], default='pending', max_length=20, verbose_name='Статусу'),
        ),
    ]
