# Generated by Django 5.2.7 on 2025-10-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_expense_order_order_type_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Күтүүдө'), ('processing', 'Аткарылууда'), ('delivered', 'Жеткирилди'), ('cancelled', 'Баш тартылды'), ('expired', 'Мөөнөтү өткөн')], default='pending', max_length=20, verbose_name='Статусу'),
        ),
    ]
