# Generated by Django 5.2.7 on 2025-11-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_order_type_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн (Касса)')], default='online', max_length=10, verbose_name='Заказдын түрү'),
        ),
    ]
