# Generated by Django 5.2.7 on 2025-11-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Жеткирүү дареги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Накталай'), ('card', 'Карта менен'), ('online', 'Онлайн (Сайт аркылуу)')], max_length=50, null=True, verbose_name='Төлөм ыкмасы'),
        ),
    ]
