# Generated by Django 5.2.7 on 2025-10-12 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категориянын аталышы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Категориянын сүрөтү')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Продукттун аталышы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сүрөттөмөсү')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баасы')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Продукттун сүрөтү')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярдуу')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Өздүк наркы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн күнү')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыртылган күнү')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продуктулар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн күнү')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Сын-пикир',
                'verbose_name_plural': 'Сын-пикирлер',
                'ordering': ['-created_at'],
            },
        ),
    ]
