# Generated by Django 5.2.7 on 2025-10-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Жарактуулук мөөнөтү'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Өндүрүлгөн күнү'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='Стоктогу саны'),
        ),
    ]
