# Generated by Django 5.2.7 on 2025-10-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_expiry_date_product_production_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Жактыруулардын саны'),
        ),
    ]
